// Generated by Selenium IDE
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using Xunit;
public class SuiteTests : IDisposable {
  public IWebDriver driver {get; private set;}
  public IDictionary<String, Object> vars {get; private set;}
  public IJavaScriptExecutor js {get; private set;}
  public SuiteTests()
  {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<String, Object>();
  }
  public void Dispose()
  {
    driver.Quit();
  }
  [Fact]
  public void LoginAndNavigation() {
    driver.Navigate().GoToUrl("https://myptclinicappapi.azurewebsites.net/");
    driver.Manage().Window.Size = new System.Drawing.Size(1296, 696);
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.CssSelector(".btn")).Click();
    driver.FindElement(By.LinkText("Appointments")).Click();
    driver.FindElement(By.CssSelector(".k-scheduler-views > .k-button:nth-child(1) > .k-button-text")).Click();
    driver.FindElement(By.CssSelector(".k-button:nth-child(2) > .k-button-text")).Click();
    driver.FindElement(By.CssSelector(".k-button:nth-child(3) > .k-button-text")).Click();
    driver.FindElement(By.CssSelector(".k-button:nth-child(4) > .k-button-text")).Click();
    driver.FindElement(By.CssSelector(".k-button:nth-child(3) > .k-button-text")).Click();
    driver.FindElement(By.LinkText("Treatments")).Click();
    {
      var element = driver.FindElement(By.LinkText("Patients"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element).Perform();
    }
    {
      var element = driver.FindElement(By.TagName("body"));
      Actions builder = new Actions(driver);
      builder.MoveToElement(element, 0, 0).Perform();
    }
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(9)")).Click();
    driver.FindElement(By.CssSelector(".btn-primary:nth-child(9)")).Click();
    driver.FindElement(By.LinkText("Reminders")).Click();
    driver.FindElement(By.CssSelector(".input-group-append > .btn")).Click();
    driver.FindElement(By.LinkText("Patients")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) > td:nth-child(3) > .btn")).Click();
    driver.FindElement(By.LinkText("Back to patient list")).Click();
    driver.FindElement(By.LinkText("Add Patient")).Click();
    driver.FindElement(By.LinkText("Back to patient list")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.LinkText("Add Patient")).Click();
    driver.FindElement(By.LinkText("Back to patient list")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.LinkText("Therapists")).Click();
    driver.FindElement(By.CssSelector("tr:nth-child(1) .fa-info-circle")).Click();
    driver.FindElement(By.LinkText("Back to therapist list")).Click();
    js.ExecuteScript("window.scrollTo(0,0)");
    driver.FindElement(By.LinkText("Monthly Stats")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".btn-success")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.LinkText("Appointment Reminders")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".btn-warning")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".btn-danger")).Click();
    driver.FindElement(By.LinkText("Home")).Click();
    driver.FindElement(By.CssSelector(".btn-link")).Click();
  }
}
